[package]
name = "fizz_buzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "FizzBuzz"
path = "../../code/412.fizz-buzz.rs"
